### ISSUE TITLE
🚀[Feature] - Potentially leverage TypeDoc to automatically generate documentation site

### ISSUE THREAD

**Issue by mrvicadai** [OctoD/tiinvo#13]
## Why?

By using automated documentation generator, the docs can be co-located with implementation and be the only source-of-truth. This will save maintenance cost as the API surface grow larger (Option, Result, Either, ..)

## What?

https://typedoc.org seems like a good option as its generated output is quite clean. An example site: https://lodin.github.io/rustils/globals.html

**Comment by mrvicadai** [comment]
(PS: Not sure how to remove the `bug` tag from this issue)

**Comment by OctoD** [comment]
Changed label 🙃 btw I think it is really a great idea! Maybe also generating the readme file with typedoc could be a nice to have, will start working tomorrow on this one.

**Comment by OctoD** [comment]
Added in #23 thank you!

**Comment by mrvicadai** [comment]
Looks great — thank you!
